task:
  name: pkg-build
  only_if: $CIRRUS_BRANCH == 'main'
  timeout_in: 120m
  container:
    dockerfile: ci/Dockerfile
    cpu: 4
    memory: 6G
  env:
    CIRRUS_WORKING_DIR: /home/builder
    CIRRUS_USER_PERMISSION: admin
  setup_docker_script: |
    sudo chown -R builder:builder .*
    sudo chown -R builder:builder *
    eval $(ssh-agent -s)
    echo "$SSH_PRIV_KEY" | tr -d '\r' | ssh-add -
    mkdir -p ~/.ssh
    touch ~/.ssh/config
    touch ~/.ssh/known_hosts
    chmod -R 400 ~/.ssh
    ssh-keyscan github.com > ~/.ssh/known_hosts
    sudo chown -R builder:builder .*
    sudo chown -R builder:builder *
    git clone git@github.com:unknownjustuser/repo.git repo
    sudo chown -R builder:builder .*
    sudo chown -R builder:builder *
    # chmod 777 *
    ls -la
    chmod +x *.sh
    ./setup.sh
  build_script: |
    ./build-pkgbuild.sh
    ./build-txt.sh
  push_script: |
    ./push.sh
