task:
  name: pkg-build
  only_if: $CIRRUS_BRANCH == 'main'
  timeout_in: 120m
  container:
    image: archlinux:base-devel
    cpu: 4
    memory: 6G
  env:
    CIRRUS_WORKING_DIR: /tmp
  setup_docker_script: |
    pacman -Syy --noconfirm --quiet --needed wget
    bash <(wget -qO- https://github.com/unknownjustuser/pkgbuild/blob/main/setup-docker.sh)
  setup_script: |
    sudo -u builder '
    sudo chown -R builder:builder .*
    sudo chown -R builder:builder *
    mkdir "$HOME"/bin
    mkdir -p "$HOME"/.local/bin
    touch "$HOME"/.gitconfig
    mkdir -p "$HOME"/.ssh
    echo "$SSH_PRIV_KEY" > "$HOME"/.ssh/id_ed25519
    chmod 600 "$HOME"/.ssh/id_ed25519
    ssh-keyscan github.com > "$HOME"/.ssh/known_hosts
    git clone git@github.com:unknownjustuser/repo.git repo
    sudo chown -R builder:builder .*
    sudo chown -R builder:builder *
    sudo chmod 777 *
    ls -al
    chmod +x *.sh
    ./setup.sh
    '
  build_script: |
    sudo -u builder '
    ./build-pkgbuild.sh
    ./build-txt.sh
    '
  push_script: |
    sudo -u builder '
    ./push.sh
    '
