task:
  name: pkg-build
  only_if: $CIRRUS_BRANCH == 'main'
  timeout_in: 120m
  container:
    image: archlinux:base-devel
    privileged: true
    cpu: 4
    memory: 6G
  deps_install_script: |
    pacman-key --init && pacman -Syy --noconfirm git make docker
  setup_script: |
    chmod +x *.sh
  build_script: |
    docker build -t my_image .
    docker run --privileged -i -v ${PWD}:/src my_image
