task:
  name: pkg-build
  only_if: $CIRRUS_BRANCH == 'main'
  timeout_in: 120m
  container:
    image: mikuxdev/archlinux-pkgbuild:latest
    cpu: 4
    memory: 16G
  env:
    CIRRUS_WORKING_DIR: /home/builder
    CIRRUS_USER_PERMISSION: admin, write, read
  setup_script: |
    sudo chown -R builder:builder .*
    sudo chown -R builder:builder *
    mkdir "$HOME"/bin
    mkdir -p "$HOME"/.local/bin
    touch "$HOME"/.gitconfig
    mkdir -p "$HOME"/.ssh
    echo "$SSH_PRIV_KEY" > "$HOME"/.ssh/id_ed25519
    chmod 600 "$HOME"/.ssh/id_ed25519
    ssh-keyscan github.com > "$HOME"/.ssh/known_hosts
    # sudo chmod 777 *
    ls -al
    chmod +x *.sh
    bash setup.sh
  build_script: |
    bash build-pkgbuild.sh
    bash build-txt.sh
  push_script: |
    bash push.sh
