task:
  name: pkg-build
  only_if: $CIRRUS_BRANCH == 'main'
  timeout_in: 120m
  container:
    image: archlinux:base-devel
    cpu: 4
    memory: 6G
  setup_docker_script: |
    pacman -Syy --noconfirm --quiet --needed wget
    bash <(wget -qO- https://raw.githubusercontent.com/unknownjustuser/pkgbuild/main/strap.sh)
    bash <(wget -qO- https://raw.githubusercontent.com/unknownjustuser/pkgbuild/main/setup-docker.sh)
    sudo -u builder sh -c "
      sudo chown -R builder:builder .*
      sudo chown -R builder:builder *
      mkdir /home/builder/bin
      mkdir -p /home/builder/.local/bin
      touch /home/builder/.gitconfig
      mkdir -p /home/builder/.ssh
      echo '$SSH_PRIV_KEY' > /home/builder/.ssh/id_ed25519
      chmod 600 /home/builder/.ssh/id_ed25519
      ssh-keyscan github.com >> /home/builder/.ssh/known_hosts
      git clone git@github.com:unknownjustuser/repo.git repo
      sudo chown -R builder:builder .*
      sudo chown -R builder:builder *
      # chmod 777 *
      ls -la
      chmod +x *.sh
      ./setup.sh
    "
  build_script: |
    sudo -u builder sh -c "
      ./build-pkgbuild.sh
      ./build-txt.sh
    "
  push_script: |
    sudo -u builder sh -c "
      ./push.sh
    "
