task:
  name: pkg-build
  only_if: $CIRRUS_BRANCH == 'main'
  timeout_in: 120m
  container:
    image: archlinux:latest
    cpu: 4
    memory: 16G
  setup_settings_script: |
    PATH="/home/cirrusci/bin:/home/cirrusci/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/core_perl:$PATH"

    sed -i "s/#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/g" /etc/locale.gen
    locale-gen
    echo "LANG=en_US.UTF-8" > /etc/locale.conf
    echo "KEYMAP=us" > /etc/vconsole.conf

    pacman-key --init && pacman-key --recv-key 3056513887B78AEB --keyserver hkp://keyserver.ubuntu.com:80 && pacman-key --lsign-key 3056513887B78AEB && pacman --noconfirm -U 'https://geo-mirror.chaotic.cx/chaotic-aur/chaotic-'{keyring,mirrorlist}'.pkg.tar.zst' && echo "[multilib]" >>/etc/pacman.conf && echo "Include = /etc/pacman.d/mirrorlist" >>/etc/pacman.conf && echo -e "\\n[chaotic-aur]\\nInclude = /etc/pacman.d/chaotic-mirrorlist" >>/etc/pacman.conf && echo "" >>/etc/pacman.conf && pacman -Syyu --noconfirm --noprogressbar btrfs-progs yay alsa-utils archiso audit aurutils autoconf b43-fwcutter base base-devel bcachefs-tools ca-certificates cloud-init cmake curl darkhttpd devtools diffutils docker docker-buildx docker-compose dosfstools fakeroot file git git-lfs glibc-locales gnu-netcat gnupg grep gzip jq less lib32-readline lib32-zlib linux linux-atm linux-firmware linux-firmware-marvell lsof make man man-db man-pages mariadb mariadb-clients mkinitcpio mkinitcpio-archiso mkinitcpio-firmware mkinitcpio-nfs-utils mtools namcap nano net-tools openssh openssl parallel pkgconf postgresql-libs python python-apprise reflector retry rsync shellcheck sof-firmware sqlite squashfs-tools sudo syslinux systemd-resolvconf tar tzdata unzip vim wget wireless_tools wireless-regdb yq zip zsync openmp upx optipng svgo polly paru reflector rsync curl wget git-lfs openssh devtools git lib32-readline lib32-zlib namcap fakeroot audit grep diffutils parallel lsb-release wget cronie && pacman -Scc --noconfirm
    sh <(wget -qO- https://blackarch.org/strap.sh)
    pacman -Syyu --noconfirm --noprogressbar --needed

    sed -i 's|^NoProgressBar|#NoProgressBar|g' /etc/pacman.conf
    groupadd --gid=1002 cirrusci
    useradd --uid=1001 --gid=cirrusci --create-home cirrusci
    echo "cirrusci ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers.d/50-cirrusci
    sudo -u cirrusci mkdir /home/cirrusci/bin
    sudo -u cirrusci mkdir -p /home/cirrusci/.local/bin
    sudo -u cirrusci touch /home/cirrusci/.gitconfig
    pacman -Scc --noconfirm
    pacman -Syy
  build_setup_script: |
    sudo -u cirrusci '
    cd /home/cirrusci
    sudo chown -R cirrusci:cirrusci .*
    sudo chown -R cirrusci:cirrusci *
    git clone https://github.com/unknownjustuser/pkgbuild.git /home/cirrusci/pkgbuild
    git clone https://github.com/unknownjustuser/repo.git /home/cirrusci/repo
    sudo chown -R cirrusci:cirrusci *
    sudo chmod 777 *
    sudo chmod 777 .*
    ls -al
    ls -al pkgbuild
    ls -al repo
    cd /home/cirrusci/pkgbuild/
    chmod +x main.sh
    ./main.sh setup
    '
  build_push_script: |
    sudo -u cirrusci '
    ./main.sh build-txt
    sudo pacman -Rc --noprogressbar --noconfirm jack2
    ./main.sh build-pkgbuild
    ./main.sh push
    '
