task:
  name: pkg-build
  only_if: $CIRRUS_BRANCH == 'main'
  timeout_in: 120m
  container:
    dockerfile: ci/Dockerfile
    cpu: 4
    memory: 16G
  env:
    CIRRUS_WORKING_DIR: /home/cirrusci
  setup_script: |
    cd /home/cirrusci
    sudo chown -R cirrusci:cirrusci .*
    sudo chown -R cirrusci:cirrusci *
    mkdir -p /home/cirrusci/.ssh
    echo "$SSH_PRIV_KEY" > /home/cirrusci/.ssh/id_ed25519
    chmod 600 /home/cirrusci/.ssh/id_ed25519
    ssh-keyscan github.com > /home/cirrusci/.ssh/known_hosts
    sudo chown -R cirrusci:cirrusci .*
    sudo chown -R cirrusci:cirrusci *
    git clone git@github.com:unknownjustuser/pkgbuild.git /home/cirrusci/pkgbuild
    cd /home/cirrusci/pkgbuild
    git checkout -f
    cd -
    git clone git@github.com:unknownjustuser/repo.git /home/cirrusci/repo
    cd /home/cirrusci/repo
    git checkout -f
    cd -
    sudo chown -R cirrusci:cirrusci .*
    sudo chown -R cirrusci:cirrusci *
    sudo chmod 777 *
    ls -al
    ls -al pkgbuild
    ls -al repo
    cd /home/cirrusci/pkgbuild/
    chmod +x main.sh
    ./main.sh setup
  build_script: |
    ./main.sh build-txt
    ./main.sh build-pkgbuild
  push_script: |
    ./main.sh push
