task:
  name: pkg-build
  only_if: $CIRRUS_BRANCH == 'main'
  timeout_in: 120m
  container:
    dockerfile: ci/Dockerfile
    cpu: 8
    memory: 32G
  env:
    CIRRUS_WORKING_DIR: /home/cirrusci
  setup_settings_script: |
    cd /home/cirrusci
    sudo chown -R cirrusci:cirrusci .*
    sudo chown -R cirrusci:cirrusci *
    git clone https://github.com/unknownjustuser/pkgbuild.git /home/cirrusci/pkgbuild
    git clone https://github.com/unknownjustuser/repo.git /home/cirrusci/repo
    sudo chown -R cirrusci:cirrusci *
    sudo chmod 777 *
    sudo chmod 777 .*
    ls -al
    ls -al pkgbuild
    ls -al repo
    cd /home/cirrusci/pkgbuild/
    chmod +x main.sh
    ./main.sh setup
  matrix:
    platforms: [build-txt, build-pkgbuild]
  build_pkgs_script: |
    if [[ $PLATFORM == "build-txt" ]]; then
      ./main.sh build-txt
    elif [[ $PLATFORM == "build-pkgbuild" ]]; then
      ./main.sh build-pkgbuild
    else
      echo "Invalid platform: $PLATFORM"
    fi
  push_pkgs_script: |
    ./main.sh push
