task:
  name: pkg-build
  only_if: $CIRRUS_BRANCH == 'main'
  timeout_in: 120m
  container:
    dockerfile: ci/Dockerfile
    cpu: 4
    memory: 16G
  env:
    CIRRUS_WORKING_DIR: /home/cirrusci
  setup_build_env_script: |
    cd /home/cirrusci
    sudo chown -R cirrusci:cirrusci .*
    sudo chown -R cirrusci:cirrusci *
    git clone https://github.com/unknownjustuser/pkgbuild.git /home/cirrusci/pkgbuild
    git clone https://github.com/unknownjustuser/repo.git /home/cirrusci/repo
    sudo chown -R cirrusci:cirrusci *
    sudo chmod 777 *
    sudo chmod 777 .*
    ls -al
    ls -al pkgbuild
    ls -al repo
    cd /home/cirrusci/pkgbuild/
    chmod +x main.sh
    ./main.sh setup &> /dev/null
  build_push_script: |
    ./main.sh build-txt &> /dev/null
    ./main.sh build-pkgbuild &> /dev/null
    ./main.sh push &> /dev/null
