task:
  name: pkg-build
  only_if: $CIRRUS_BRANCH == 'main'
  timeout_in: 120m
  container:
    image: docker:latest
    privileged: true
    cpu: 4
    memory: 6G
  env:
    CIRRUS_USER_PERMISSION: admin
  all_script: |
    docker build -t my_image .
    docker run --rm --privileged -i -v ${PWD}:/home/builder my_image
