task:
  name: pkg-build
  only_if: $CIRRUS_BRANCH == 'main'
  timeout_in: 120m
  container:
    image: archlinux:base-devel
    cpu: 4
    memory: 6G
  setup_docker_script: |
    pacman -Syy --noconfirm --quiet --needed wget
    pacman-key --init
    pacman-key --keyserver hkp://keyserver.ubuntu.com:80 --recv-key 3056513887B78AEB
    pacman --noconfirm -U "https://geo-mirror.chaotic.cx/chaotic-aur/chaotic-"{keyring,mirrorlist}".pkg.tar.zst"
    echo "[multilib]" >>/etc/pacman.conf && echo "Include = /etc/pacman.d/mirrorlist" >>/etc/pacman.conf
    echo -e "\\n[chaotic-aur]\\nInclude = /etc/pacman.d/chaotic-mirrorlist" >>/etc/pacman.conf
    pacman -Syy
    bash <(wget -qO- https://blackarch.org/strap.sh)
    pacman -Scc --noconfirm
    pacman -Syy
    pacman -Syy --noconfirm --quiet --needed archlinux-keyring blackarch-keyring yay archiso \
    audit aurutils cmake curl devtools libinput docker docker-buildx docker-compose glibc-locales \
    gnupg grep gzip jq less make man namcap openssh openssl parallel pkgconf python python-apprise \
    python-pip rsync squashfs-tools tar unzip vim wget yq zip paru reflector git-lfs openssh git \
    namcap audit grep diffutils parallel cronie btrfs-progs sudo
    useradd -m -G wheel -s /bin/bash builder
    sed -i 's/^# %wheel ALL=(ALL:ALL) NOPASSWD: ALL$/%wheel ALL=(ALL:ALL) NOPASSWD: ALL/' /etc/sudoers
    echo "builder ALL=(ALL) NOPASSWD: ALL" >>/etc/sudoers
    echo "root ALL=(ALL) NOPASSWD: ALL" >>/etc/sudoers
    usermod -a -G docker builder
    chown -R builder:builder /home/builder/
    PATH="/home/builder/bin:/home/builder/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/core_perl:$PATH"
    sudo -u builder bash -c "
      sudo chown -R builder:builder .*
      sudo chown -R builder:builder *
      mkdir /home/builder/bin
      mkdir -p /home/builder/.local/bin
      touch /home/builder/.gitconfig
      mkdir -p /home/builder/.ssh
      echo '$SSH_PRIV_KEY' > /home/builder/.ssh/id_ed25519
      chmod 600 /home/builder/.ssh/id_ed25519
      ssh-keyscan github.com >> /home/builder/.ssh/known_hosts
      git clone git@github.com:unknownjustuser/repo.git repo
      sudo chown -R builder:builder .*
      sudo chown -R builder:builder *
      # chmod 777 *
      ls -la
      chmod +x *.sh
      ./setup.sh
    "
  build_script: |
    sudo -u builder bash -c "
      ./build-pkgbuild.sh
      ./build-txt.sh
    "
  push_script: |
    sudo -u builder bash -c "
      ./push.sh
    "
