version: 2.1

jobs:
  build-image:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t archfiery .

  setup:
    docker:
      - image: archfiery
    resource_class: large
    working_directory: /home/circleci
    steps:
      - checkout:
          path: /home/circleci/pkgbuild
      - run:
          name: build_push
          command: |
            cd /home/cirrusci
            git clone https://github.com/unknownjustuser/repo /home/circleci/repo
            ./main.sh setup

            cd /home/cirrusci
            ./main.sh build-txt
            sudo pacman -Rc --noprogressbar --noconfirm jack2
            ./main.sh build-pkgbuild

            cd /home/cirrusci
            sudo chown -R circleci output/*
            ./main.sh push

workflows:
  build-and-setup:
    jobs:
      - build-image
      - setup:
          requires:
            - build-image
